### ISSUE TITLE
Dummy Enumeration - ACTIVITY IDENTIFIER - should be fixed with issue 76

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#29]
For discussion, ACTIVITY IDENTIFIER has Code	Description, Dummy Enumeration	Dummy

**Comment by maxChappell** [comment]
This is because although the attribute itself carries NO national codes...some of the data elements have default codes defined - and fhir generation app was incorrectly posting them to ontoserver. This is fixed with #76 

Next action will be to rollback onto server affected items - and re-run steve processing.

**Comment by likin1** [comment]
Hi,
I have tested this and this item is not getting generated as there no national codes. So its fixed

**Comment by maxChappell** [comment]
agreed
