### ISSUE TITLE
Submit Proposal for the implemented architecture to TRG

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#306]
Technical Architecture to work with Mauro team with support from Data Products to describe the proposal for the implemented architecture and to take this proposal to TRG for review, feedback and suggestions of refinements.

**Comment by AngelaFaulding** [comment]
21/12/21 - Nothing that is working has gone through TRG for approval yet.

**Comment by AngelaFaulding** [comment]
The Orchestration Tool will be covered in TRG approval. What impact does it have on the technical architecture?

**Comment by PaulChapmanPM** [comment]
I have invited data products, technical architecture and enterprise architecture colleagues to a meeting to discuss completion of the documentation for submission to TRG. This has needed to be rescheduled to 6 January due to covid work pressures on TA.  @AngelaFaulding, I've now added you to the invite.

**Comment by PaulChapmanPM** [comment]
Delayed again due to architecture availability (due to COVID work) and then knocked on again due to key personnel on holiday. Next meeting on this 24 Jan.

**Comment by PaulChapmanPM** [comment]
Ticket #367 created to combine #272, #278 and #306

**Comment by GSChandel** [comment]
Closing as now created as part of the new ticket.
