### ISSUE TITLE
Mauro User Categories

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#409]
Currently, all DD users are set as administrators.
Can this be changed so there are other groups, such as author?
We don't want authors to be able to carry out specific tasks, e.g. move certain folders, publish releases, perform Ontoserver Integration.
Discussed with James 7/3/22 who says this is possible for the AWS instance.

**Comment by GSChandel** [comment]
Moved back to 'To Do' as not currently in progress and not part of S13.

**Comment by jamesrwelch** [comment]
Favourites are updated as per #443.  Final task is to restrict button presses in the orchestrator to only allow certain operations to be performed by particular users.

**Comment by jamesrwelch** [comment]
Favourites updated so that they can be expanded
<img width="574" alt="Screenshot 2022-09-07 at 21 24 22" src="https://user-images.githubusercontent.com/1869668/188970681-a0ef8d66-ba0c-4bd8-8223-bc21c2303170.png">


User / Group permissions applied to certain items in the orchestrator so that only members of a particular user group can carry them out.  Otherwise, a warning message is shown:

<img width="849" alt="Screenshot 2022-09-07 at 21 24 32" src="https://user-images.githubusercontent.com/1869668/188970591-6c048266-5742-430a-9b6a-fc736ebd976b.png">

**Comment by AngelaFaulding** [comment]
To test this I removed myself from the Terminology Server Administrators group:
![image](https://user-images.githubusercontent.com/62995711/193544920-2208f079-0536-4df8-ae9c-7fbc79b1fca1.png)

But when I go back in I am still in the group so am unable to test whether I would receive the error above:
![image](https://user-images.githubusercontent.com/62995711/193545251-df52c9b7-c650-457f-98aa-cba6bc9c8bed.png)

**Comment by AngelaFaulding** [comment]
@jamesrwelch - we asked Peter if we could remove the unnecessary groups and he wasn't sure so he will ask you.
We ideally only want the groups we need now and in the future.
We created the first two last time and would like to keep the Terminology one for post migration (renamed to say that)

![image](https://github.com/NHSDigital/DataDictionaryPublication/assets/62995711/6be6a154-29c9-4ebc-a50d-5b748cfa0d26)

**Comment by AngelaFaulding** [comment]
25/06/24 - comments from Peter Monks:
Just checked, you can rename the "administrators" user group to whatever you want, everyone in that group will remain an administrator

The "Terminology Server Administrators" and "Website Preview Generators" user groups have been hard coded into the Mauro plugin you use, so if you want them removed I'll need to work on that at the same time as removing administrator restrictions to the orchestrator

Regarding the user groups in the style "angela.faulding@nhs.net Group", when a user creates something and they aren’t in any group, one has to be created for the ‘readable by’ field, otherwise that user won’t be able to see it. So it's automatically happening. It's something James intends to change in the future but have no timeframe for that. I suppose for now you could create something e.g. a folder, then go back and assign a different user group to it, then remove the auto created one

**Comment by AngelaFaulding** [comment]
We need all user groups be able to access the Orchestrator.

We don't need "Website Preview Generators" but would like to retain "Terminology Server Administrators" and rename it.
We can look at the groups again in Post Migration and use "Terminology Server Administrators". I have raised a new issue for Post Migration to consider this.

**Comment by stevebowring** [comment]
On accessing Mauro and selecting **Browse** I get a long loading time (rotating arrows), then:

- No Model + Red Server Error message 'We're sorry but the server responded with an error message"
- On clicking away to **Search** and back to **Browse** I can then see the model 'Data Dictionary & branches etc'

**Comment by stevebowring** [comment]
On attempting to access Orchestrator - the **Sign in** doesn't accept me as a user - Error message 'Unable to sign in.  Please try later'

**Comment by GSChandel** [comment]
My screen after logging in 
<img width="934" alt="image" src="https://github.com/NHSDigital/DataDictionaryPublication/assets/68650276/ab17a89c-98fd-4cc9-a4a8-1e15e3513677">

**Comment by GSChandel** [comment]
<img width="932" alt="image" src="https://github.com/NHSDigital/DataDictionaryPublication/assets/68650276/3c56cca5-811d-403e-9396-f279f276b1a1">
Now can access what I need to

**Comment by AngelaFaulding** [comment]
@pjmonks - This is Gouri's screen. He is an editor and can't access the Orchestrator.

![image](https://github.com/NHSDigital/DataDictionaryPublication/assets/62995711/f95f8f7c-f635-43f6-8252-12bbd60a7366)

**Comment by AngelaFaulding** [comment]
Peter said that "The "Terminology Server Administrators" and "Website Preview Generators" user groups have been hard coded into the Mauro plugin you use, so if you want them removed I'll need to work on that at the same time as removing administrator restrictions to the orchestrator".
I believe that all groups should now be able to access the Orchestrator but "Terminology Server Administrators" and "Website Preview Generators" still exists.
Also, what is the group "administrators" for? We are using "administrators".

![image](https://github.com/NHSDigital/DataDictionaryPublication/assets/62995711/fa487e93-58d4-40ef-9481-834580fdbe2a)

**Comment by pjmonks** [comment]
The user groups "Terminology Server Administrators" and "Website Preview Generators" are safe to delete now, this can be done by any administrator. System C have made sure that they have no bearing on actions done in Mauro or the Orchestrator.

The additional administrators group looks like a user group that has been automatically added back in by Mauro itself. My suspicion is that Mauro has "bootstrapped" this user group because it was not found - at startup of the web application, several automated actions happen to ensure the correct state of Mauro. If it did not find an "administrator" group (case sensitive), then it looks like it created one for you.

Both named administrator groups have the "Administrator" group role, so anyone in either group is considered an administrator. My suggestion is to either:

1. Delete the "Administrators" group and move all users to the "administrators" group, keeping that name for the future. Or
2. Raise an issue to @jamesrwelch to look into a possible bug to fix.

**Comment by AngelaFaulding** [comment]
Closed and replaced with #485
