### ISSUE TITLE
Mauro Search

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#484]
As discussed with Peter on 9 July 23024, we have been looking at the Search in Mauro.
We need further clarification on how this should work.
It looks like it is something we would use if it works as it suggests.

As an example, I searched for gender in Branch CR800

![image](https://github.com/NHSDigital/DataDictionaryPublication/assets/62995711/dc1ee3ee-faa5-4101-b078-5dfc53b69a60)

However, it produced items from other branches, including CR1903, CR1883, main branch, CR1915 etc.

![image](https://github.com/NHSDigital/DataDictionaryPublication/assets/62995711/e97dbf04-68cc-4d57-b003-8781b0f1072d)

**Comment by AngelaFaulding** [comment]
Peter - can you please explain when we would use this and when we would use the search on the folders. It seems to do the same thing.

![image](https://github.com/NHSDigital/DataDictionaryPublication/assets/62995711/7ffc9c4a-905e-43ea-9d58-592630ac4bfd)

**Comment by pjmonks** [comment]
@AngelaFaulding The global search seems to not be using the Versioned Folder you selected as a filter correctly, which is why more search results are returned as expected. I think the global search is out of scope for our project, so this should be raised to @jamesrwelch .

Your other question related to this screen:

![image](https://github.com/user-attachments/assets/7278e663-d4fc-40be-a69b-43d0c26937af)

That is meant to be a search localised only for that folder (or model) down, so it should return just search results for that versioned folder directly. It also has less search filter options, so it will always search for labels that match and cannot be filtered any further. I have found that this also returns too many search results, the parent folder in view is not being used as a search filter. This is in scope for our project, so I have created MauroDataMapper/mdm-ui#880 to fix this.

**Comment by AngelaFaulding** [comment]
@jamesrwelch  - please see Peter's comments above.
Do people use the global search and it is something we would want to use?
If so, does it need looking into?

**Comment by AngelaFaulding** [comment]
16/07/2024 - James doesn't think we need to use the global search if the folder search works.
We can't use bulk edit for descriptions as it only searches at one folder at a time and by name.
This could be new functionality in the Orchestrator but is not currently part of the SOW.
We need something to search for retired items so the last release and date can be added.

**Comment by pjmonks** [comment]
@AngelaFaulding I have been double checking the search tab under a data dictionary branch, like this:

![image](https://github.com/user-attachments/assets/bac97a78-69cf-4964-8e4a-31375e78cbd0)

I've found that, actually, the search results returned are all from underneath the chosen branch, so my earlier comment was incorrect. I have noticed it is slow to search through an entire branch, but the search tab is present on other sub-folder/items under the branch too e.g. click on "Classes and Attributes" and you can search directly for a class/attribute which should be faster.

I think this search tab will ultimately help with navigability around the branch.

**Comment by AngelaFaulding** [comment]
23/07/24 - James has confirmed that the global search is not helpful to us.
We will use the folder search.
