### ISSUE TITLE
Clinical data sets

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#62]
For consistency, can Data Sets be removed from:
- DataSets: cancer outcomes and services data set
- DataSets: national neonatal data set

Comment still valid, I can understand why this has happened, but it doesn’t look consistent

**Comment by maxChappell** [comment]
Not sure who needs to action/answer this

**Comment by arkie-boy** [comment]
Can you supply some more detail about what page you found this on, James?  I'm having difficulty finding it amongst all the different HTML tags that are on the pages - I suspect at least part of that string is the text for an anchor tag of some kind.

**Comment by jamesrwelch** [comment]
This one was originally @AngelaFaulding , I just transcribed it.  I assume it's in the headings / index pages, and I assume it's my fault

**Comment by maxChappell** [comment]
Hi Angela - can you give some more detail please?

**Comment by AngelaFaulding** [comment]
https://beta.datadictionary.nhs.uk/data_sets/clinical_data_sets.html has:
Data Sets: Cancer Outcomes and Services Data Set
Data Sets: National Neonatal Data Set

It is because there are more than one of these data sets. The link takes you to another page where you select the data set.
The current version is correct: see https://www.datadictionary.nhs.uk/web_site_content/navigation/clinical_data_sets_menu.asp?shownav=1

**Comment by AngelaFaulding** [comment]
Extra page removed so ticket closed.
