### ISSUE TITLE
Treatment function code list includes † as a code - special characters

### ISSUE THREAD

**Issue by oughnic** [NHSDigital/DataDictionaryPublication#74]

**Comment by oughnic** [comment]
See https://beta.datadictionary.nhs.uk/data_elements/a/act/activity_treatment_function_code.html

**Comment by maxChappell** [comment]
Initial investigation complete. Possible fix identified. First need to verify that DD codes have only ever AND will only ever be alphanumeric. Otherwise much trickier to fix

Treatment function code
† showing as a concept
This is not correct.
See https://www.datadictionary.nhs.uk/archive/DD%20Release%20May%202019/data_dictionary/attributes/t/tran/treatment_function_code_de.asp?shownav=1
It was a footnote re usage.
Need to check with DD team cut I don’t think any DD codes contain anything other than alphanumerics….Could be one way to exclude from fhir items….
OR – this item was in a standalone table – without a National Codes label above….tricky I know because so many tables are used in the html….
Note the dagger has been removed on most recent release.

**Comment by maxChappell** [comment]
[Special Characters_June 2020.xlsx](https://github.com/NHSDigital/DataDictionaryPublication/files/4994046/Special.Characters_June.2020.xlsx)

**Comment by maxChappell** [comment]
File above provides listing and examples of instances of special characters that need unicode changes for ontoserver processing.

Need to have a think about if any of these special characters may appear in non-national code content (although I think steve's processing already handles them probably).

**Comment by likin1** [comment]
Hi, this has been fixed.

**Comment by maxChappell** [comment]
agreed
