### ISSUE TITLE
Area of Work Name - no longer generated to ontoserver - but table with codes not in the expanded xml file 

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#95]
https://beta.datadictionary.nhs.uk/attributes/a/ar/area_of_work_name.html
The National Codes are not in the beta version. It is a different type of table.

**Comment by maxChappell** [comment]
This item should not be getting generated at all. (No National Codes heading). Should be fixed when #76 applied.

**Comment by maxChappell** [comment]
Prior comment incorrect - "national codes" does appear for this attribute. However, it is a multi-level code list and we are not currently supposed to be generating them.

**Comment by likin1** [comment]
Hi,

AREA_OF_WORK_NAME has been fixed.It will not be sent to ontoserver server

**Comment by maxChappell** [comment]
The table containing the codes is not getting added to the expanded xml file. Noted that "National Codes:" does appear before the table. Steve's processing now gets nothing back from ontoserver (which is correct as this is a multi-level table).

Can see 2 possible approaches to resolving this:
1) Steve's logic amended to grab the remaining html - after hitting ontoserver and getting a zero return. OR
2) DD team to remove or change the label, so that Steve's processing isn't expecting anything from ontoserver and thus grabs the entire contents of $doc by default

**Comment by cach1** [comment]
For discussion - if time is an issue for fixing we could remove the whole table and refer user to NWD data set page here https://digital.nhs.uk/data-and-information/data-collections-and-data-sets/data-sets/national-workforce-data-set-nwd-and-nhs-occupation-codes @AngelaFaulding
